"""initial migration

Revision ID: 81e91245d5be
Revises: 
Create Date: 2024-11-16 01:44:27.508144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e91245d5be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_group_creator_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('is_settled', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='fk_expense_group_id'),
    sa.ForeignKeyConstraint(['payer_id'], ['user.id'], name='fk_expense_payer_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='fk_group_members_group_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_group_members_user_id'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('expense_split',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_settled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], name='fk_expensesplit_expense_id'),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], name='fk_split_expense_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_expensesplit_user_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_split_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_split')
    op.drop_table('group_members')
    op.drop_table('expense')
    op.drop_table('group')
    op.drop_table('user')
    # ### end Alembic commands ###
